#!/bin/sh

# https://www.minecraft.net/en-us/download/server/
# java -Xmx1024 -Xms1024 -jar server.jar nogui

# https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
cmd="java -Xmx4G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -jar server.jar nogui"

if [ "$1" == "start" ]
then
    tmux new-session -s minecraft -d "$cmd"
fi

if [ "$1" == "stop" ]
then
    tmux send-keys -t minecraft 'say SERVER SHUTTING DOWN. Saving map...' C-m 'save-all' C-m 'stop' C-m
    sleep 15
fi

if [ "$1" == "save-on" ]
then
    tmux send-keys -t minecraft 'save-on' C-m 'say Backup complete!' C-m
fi

if [ "$1" == "save-off" ]
then
    tmux send-keys -t minecraft 'say Backup process starting...' C-m 'save-off' C-m 'save-all' C-m
fi

